- name: Playbook to deploy the HAProxy
  hosts: frontends
  gather_facts: true # remove later! speeds up testing
  become: true

  tasks:
    - name: Deploy and configure HAProxy
    - block:
      - name: Deploy latast version of HAProxy
        yum:
          name: haproxy
          state: latest
      - name: Coonfigure HAProxy
        template:
          src: templates/haproxy.cfg.j2
          dest: /etc/haproxy/haproxy.cfg
      notify: enable_and_start_haproxy_service 
  handlers:
    - name: enable_and_start_haproxy_service
      service:
        name: haproxy
        state: restarted
        enabled: true