---
- name: Deploy and configure Three-tier app environment
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: Enabled internal repositories
    template:
      src: files/open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: Import playbook to deploy the backend app
  import_playbook: playbooks/deploy_{{ backend_app }}.yml
  tags: backend

- name: Import playbook to deploy the frontend app
  import_playbook: playbooks/deploy_{{ frontend_app }}.yml
  tags: frontend

- name: Import playbook to deploy the database
  import_playbook: playbooks/deploy_{{ database_app }}.yml
  tags: database