- name: Playbook to deploy the HAProxy
  hosts: frontends
  gather_facts: true # remove later! speeds up testing
  become: true
  
  vars:
    packages_needed:
      - httpie
      - haproxy
  
  tasks:
  
    - name: Deploy latast version of HAProxy
      package:
        name: "{{ packages_needed }}"
        state: latest
      notify: enable_and_start_haproxy_service 
  
    - name: Configure HAProxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: enable_and_start_haproxy_service 
  
  handlers:
    - name: enable_and_start_haproxy_service
      service:
        name: haproxy
        state: restarted
        enabled: true